server:
  port: 8080
  servlet:
    context-path: /api/v1/dropio

spring:
  application:
    name: dropio
  datasource:
    url: jdbc:postgresql://localhost:5432/dropio
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    show-sql: true

# storage
storage:
  root-path: file


logging:
  level:
    web: info
